# Generated by Django 5.1.3 on 2024-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flipkart', '0004_alter_product_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(default='Available', max_length=1000),
        ),
    ]
