# Generated by Django 5.1.3 on 2024-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flipkart', '0005_alter_product_ratings_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(default=4),
        ),
    ]
