# Generated by Django 5.1.3 on 2024-11-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flipkart', '0006_alter_product_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
