# Generated by Django 5.1.1 on 2024-11-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flipkart', '0007_alter_product_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_color',
            field=models.CharField(default='#FFA500', max_length=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
        ),
    ]
