# Generated by Django 5.1.1 on 2024-11-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flipkart', '0009_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='star_color',
        ),
    ]
